const data=[
{id:"luggo",title:"Luggo Vilas Parque",fin:"Comprar",type:"Apartamento",loc:"Lauro de Freitas, BA",rooms:2,area:"Consulte",price:"Consulte",img:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=90",desc:"Condomínio residencial em uma região estratégica de Lauro de Freitas."},
{id:"sensia",title:"Sensia Patamares",fin:"Comprar",type:"Apartamento",loc:"Patamares, Salvador, BA",rooms:3,area:"Consulte",price:"Consulte",img:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=90",desc:"Residencial contemporâneo com localização privilegiada."},
{id:"joanes",title:"Vista do Joanes",fin:"Comprar",type:"Apartamento",loc:"Bahia",rooms:3,area:"Consulte",price:"Consulte",img:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=90",desc:"Conforto e praticidade para morar ou investir."}
];
let f="Todos";const grid=document.getElementById("grid");
function render(){let q=document.getElementById("q").value.toLowerCase(),t=document.getElementById("t").value,r=document.getElementById("r").value,n=r==="Todos"?0:+r[0];let a=data.filter(x=>(f==="Todos"||x.fin===f)&&(t==="Todos"||x.type===t)&&(!q||x.loc.toLowerCase().includes(q))&&(!n||x.rooms>=n));document.getElementById("count").textContent=a.length+" imóvel(is)";grid.innerHTML=a.map(x=>`<article class="card" onclick="openDetail('${x.id}')"><div class="photo" style="background-image:url('${x.img}')"><b>${x.fin.toUpperCase()}</b></div><div class="cardBody"><small>${x.loc}</small><h3>${x.title}</h3><p>${x.type} • ${x.rooms} quartos • ${x.area} m²</p><span class="price">${x.price}</span><span class="see">Ver detalhes →</span></div></article>`).join("")||"<p>Nenhum imóvel encontrado.</p>"}
document.querySelectorAll(".purpose button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".purpose button").forEach(x=>x.classList.remove("sel"));b.classList.add("sel");f=b.dataset.f;render()});
document.getElementById("go").onclick=render;document.getElementById("t").onchange=render;document.getElementById("r").onchange=render;
function openDetail(id){let x=data.find(y=>y.id===id);document.getElementById("detail").innerHTML=`<div class="detail"><div class="detailImg" style="background-image:url('${x.img}')"></div><div class="detailText"><small>${x.fin} • ${x.type}</small><h2>${x.title}</h2><p>${x.loc}</p><div class="specs"><div><b>${x.rooms}</b><span>Quartos</span></div><div><b>${x.area}</b><span>Área</span></div><div><b>—</b><span>Vagas</span></div></div><h3>${x.price}</h3><p>${x.desc}</p><a class="goldbtn" href="https://wa.me/?text=Olá! Tenho interesse no imóvel ${encodeURIComponent(x.title)}." target="_blank">Tenho interesse pelo WhatsApp</a></div></div>`;document.getElementById("modal").classList.add("open")}
document.getElementById("close").onclick=()=>document.getElementById("modal").classList.remove("open");document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")e.currentTarget.classList.remove("open")};render();